---
title: "FinalProjectRD"
author: "Zoe Bean"
date: "11/18/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r import}

make_data<-read_csv("Group+Projects+2021_all_numeric.csv", col_select = c(Q13.1,Q13.2,Q13.3,Q14.1,Q14.2,Q14.3,Q15.1,Q15.2,Q15.3,Q16.1_1,Q16.1_2,	Q16.1_3,Q16.1_4, Q18.6)) #selects only our question columns
make_data<-make_data[-c(1:2),] #remove rows not number data
write_csv(make_data, "media_data.csv") #make new dataset csv

remove(make_data) #remove extra dataset
media_data<-read_csv("media_data.csv") #now open csv so that all variables register as numbers and not characters

```

```{r newcolumn}
# adjust reverse scored questions
media_data<-media_data %>% mutate(Q16.1_2= case_when( Q16.1_2==5~1, Q16.1_2==4~2, Q16.1_2==2~4,Q16.1_2==3~3,  Q16.1_2==1~5), Q16.1_3= case_when( Q16.1_3==5~1, Q16.1_3==4~2,Q16.1_3==3~3, Q16.1_3==2~4, Q16.1_3==1~5))

#add new columns
media_data<-media_data %>% 
  mutate(mood= case_when( 
    !is.na(Q13.1) | !is.na(Q13.2) | !is.na(Q13.3) ~ 'neutral', #if 13.1, 13.2, 13.3 have answer post mood= neutral
    !is.na(Q14.1) | !is.na(Q14.2 | !is.na(Q14.3))  ~ 'stress', #if 14.1, 14.2, 14.3 have answer post mood= stress
    !is.na(Q15.1) | !is.na(Q15.2) | !is.na(Q15.3) ~ 'happy' ),#if 359, 360, 361 have answer post mood= happy
    
    score= Q16.1_1+Q16.1_2+Q16.1_3+Q16.1_4, #the score of the stress scale 
    age=case_when( #age
      Q18.6==1 ~'18-25',
      Q18.6==2 ~'26-35',
      Q18.6==3 ~'36-45',
      Q18.6==4 ~'46-60',
      Q18.6==5 ~'61+',
    ),
    
    color=case_when(
      mood=='happy'~'green',
      mood=='neutral'~'yellow',
      mood=='stress'~'red'
    )
    ) 

media_data <- filter(media_data, rowSums(is.na(media_data)) != ncol(media_data)) #removing the rows that are all NAs
```


```{r analysis}

#overall mood
ggplot(data=media_data, aes(score)) +
  geom_bar() + facet_wrap(~mood)
ggsave("bar_mood.png", device="png", width=10, height=8, units="in",dpi=300)

ggplot(data = media_data, mapping = aes(x = mood, y = score)) +
    geom_boxplot()
ggsave("box_mood.png", device="png", width=10, height=8, units="in",dpi=300)

media_data%>%group_by(mood)%>%summarize(mean(score), median(score), min(score), max(score))

#overall age
ggplot(data=media_data, aes(score, fill=mood)) +
  geom_bar() + facet_wrap(~age)
ggsave("bar_age.png", device="png", width=10, height=8, units="in",dpi=300)

ggplot(data = media_data, mapping = aes(x = age, y = score)) +geom_boxplot()
ggsave("box_age.png", device="png", width=10, height=8, units="in",dpi=300)

media_data%>%group_by(age)%>%summarize(mean(score), median(score), min(score), max(score))

#age divided, stressed
ggplot(data=filter(media_data, mood=='stress'), aes(score)) +
  geom_bar() + facet_wrap(~age) +labs(title='stress')
ggsave("bar_mood_stress.png", device="png", width=10, height=8, units="in",dpi=300)

ggplot(data = filter(media_data, mood=='stress'), mapping = aes(x = age, y = score)) +
  geom_boxplot() +labs(title='stress')
ggsave("box_mood_stress.png", device="png", width=10, height=8, units="in",dpi=300)

media_data%>%filter(mood=='stress')%>%group_by(age)%>%summarize('stressed average score'=mean(score), median(score), min(score), max(score))

#age divided,happy
ggplot(data=filter(media_data, mood=='happy'), aes(score)) +
  geom_bar() + facet_wrap(~age) +labs(title='happy')
ggsave("bar_mood_happy.png", device="png", width=10, height=8, units="in",dpi=300)

ggplot(data = filter(media_data, mood=='happy'), mapping = aes(x = age, y = score)) +
  geom_boxplot() +labs(title='happy')
ggsave("box_mood_happy.png", device="png", width=10, height=8, units="in",dpi=300)

media_data%>%filter(mood=='happy')%>%group_by(age)%>%summarize('happy average score'=mean(score), median(score), min(score), max(score))

#age divided, neutral
ggplot(data=filter(media_data, mood=='neutral'), aes(score)) +
  geom_bar() + facet_wrap(~age) +labs(title='neutral')
ggsave("bar_mood_neutral.png", device="png", width=10, height=8, units="in",dpi=300)

ggplot(data = filter(media_data, mood=='neutral'), mapping = aes(x = age, y = score)) +
  geom_boxplot() +labs(title='neutral')
ggsave("bix_mood_neutral.png", device="png", width=10, height=8, units="in",dpi=300)

media_data%>%filter(mood=='neutral')%>%group_by(age)%>%summarize('neutral average score'=mean(score), median(score), min(score), max(score))

#mood divided by age
ggplot(data=filter(media_data, age=='18-25'), aes(score, fill=mood)) +
  geom_bar() + facet_wrap(~mood) +labs(title='18-25')
ggsave("bar_age_18_25.png", device="png", width=10, height=8, units="in",dpi=300)

ggplot(data = filter(media_data, age=='18-25'), mapping = aes(x = mood, y = score, fill=mood)) +
  geom_boxplot() +labs(title='18-25')
ggsave("box_age_18_25.png", device="png", width=10, height=8, units="in",dpi=300)

ggplot(data=filter(media_data, age=='26-35'), aes(score, fill=mood)) +
  geom_bar() + facet_wrap(~mood) +labs(title='26-35')
ggsave("bar_age_26_35.png", device="png", width=10, height=8, units="in",dpi=300)

ggplot(data = filter(media_data, age=='26-35'), mapping = aes(x = mood, y = score, fill=mood)) +
  geom_boxplot() +labs(title='26-35')
ggsave("box_age_26_35.png", device="png", width=10, height=8, units="in",dpi=300)

ggplot(data=filter(media_data, age=='36-45'), aes(score, fill=mood)) +
  geom_bar() + facet_wrap(~mood) +labs(title='36-45')
ggsave("bar_age_36_45.png", device="png", width=10, height=8, units="in",dpi=300)

ggplot(data = filter(media_data, age=='36-45'), mapping = aes(x = mood, y = score, fill=mood)) +
  geom_boxplot() +labs(title='36-45')
ggsave("box_age_36_45.png", device="png", width=10, height=8, units="in",dpi=300)

ggplot(data=filter(media_data, age=='46-60'), aes(score, fill=mood)) +
  geom_bar() + facet_wrap(~mood) +labs(title='46-60')
ggsave("bar_age_46_60.png", device="png", width=10, height=8, units="in",dpi=300)

ggplot(data = filter(media_data, age=='46-60'), mapping = aes(x = mood, y = score, fill=mood)) +
  geom_boxplot() +labs(title='46-60')
ggsave("box_age_46_60.png", device="png", width=10, height=8, units="in",dpi=300)

ggplot(data=filter(media_data, age=='61+'), aes(score, fill=mood)) +
  geom_bar() + facet_wrap(~mood) +labs(title='61+')
ggsave("bar_age_61plus.png", device="png", width=10, height=8, units="in",dpi=300)

ggplot(data = filter(media_data, age=='61+'), mapping = aes(x = mood, y = score, fill=mood)) +
  geom_boxplot() +labs(title='61+')
ggsave("box_age_61plus.png", device="png", width=10, height=8, units="in",dpi=300)
```